### ISSUE TITLE
Extend the facade classes instead of the actual class

### ISSUE THREAD

**Issue by danielboendergaard** [jonphipps/laravel4-idehelper-generator#3]
Instead of extending the classes where you get the methods from, the generated classes should instead extend the facades. That will prevent all the redefine function as static errors and will also provide autocompletion for the methods defined in the Facade class.

I don't really see any advantages of extending the classes as you do now. The only one I can think of is if you are going to create a new instance of the class like `new Class` but akaik all classes has a make method which takes care of that.

**Comment by jonphipps** [comment]
Good point. I updated the code to extend the façade wherever possible and added a bit of documentation to each class to note what class was being returned by the façade/factory. It's in the latest version.

Things are better, but perfection remains elusive.
