### ISSUE TITLE
i've got error

### ISSUE THREAD

**Issue by matiaspub** [jonphipps/laravel4-idehelper-generator#7]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jonphipps/idehelper dev-master -> satisfiable by jonphipps/idehelper[dev-master].
    - jonphipps/idehelper dev-master requires illuminate/support 4.0.x -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

**Comment by jonphipps** [comment]
Yeah, I got that too after the Laravel/framework dev-master became based on 4.1 instead of 4.0. I changed the composer requirement to 4.0.\* which seems to work ok at the moment. Have to keep an eye on it though.
